### ISSUE TITLE
Request for Opera Extension

### ISSUE THREAD

**Issue by UncleInf** [slgobinath/uget-chrome-wrapper#10]
Vast majority of applications written for chrome does work correctly on opera using [link](https://addons.opera.com/en-gb/extensions/details/download-chrome-extension-9/). This is possible due to the fact that opera is based on chromium. Sadly after successfully trying plugin on chrome it doesn't work on opera. I've skimmed through opera API and NativeMessagingHosts message sending should be the same, but I didn't manage to debug further.

**Comment by slgobinath** [comment]
Hi,
Did follow the manual installation method for chromium & Vivaldi? Opera uses the settings of Google Chrome. Install the uget-chrome-wrapper for Google Chrome and test it with Opera. According to my system (Linux Mint 18, Opera 42.0, uget-chrome-wrapper installed using apt) uGet Integration works as expected.

**Comment by ForceBro12** [comment]
I don't know what happen, but opera is slightly different from chromium and vivaldi. It won't install extensions from chrome extension website (chrome webstore), but it can be installed manually by downloading the .crx file. I use [this website](http://chrome-extension-downloader.com) to download the crx file, open the extension manager (extensions - manage extensions), drag and drop the crx file, and the extension successfully installed.

For the dev(s), maybe you can create the crx file and put it on github so opera users can install it, or make it available on opera store.

**Comment by slgobinath** [comment]
I have submitted the addon to Opera. Once it is approved, Opera users can enjoy the addon with less effort :)

**Comment by slgobinath** [comment]
Until Opera extension is approved, you can use [Download Chrome Extension](https://addons.opera.com/extensions/details/app_id/kipjbhgniklcnglfaldilecjomjaddfi) to install the addon. 

Step 1. Install the  [Download Chrome Extension](https://addons.opera.com/extensions/details/app_id/kipjbhgniklcnglfaldilecjomjaddfi) addon
Step 2: Visit to [uGet Integration web store](https://chrome.google.com/webstore/detail/uget-integration/efjgjleilhflffpbnkaofpmdnajdpepi)
Step 3: Click on `Add to Opera`
Step 4: Click `OK` on the message dialog
Step 5: Click `Install` next to the uGet Integration addon in the addon manager
Step 6: Install `uget-chrome-wrapper` and restart the Opera

Tested on Opera 43.0 with uGet 2.0.9 in Linux Mint 18.1.

FYI: uget-chrome-wrapper 2.0.0 along with the browser extension is released few minutes ago :-)

**Comment by slgobinath** [comment]
Hi @UncleInf, @ForceBro12,
I am pleased to inform you that the Opera extension is now available at https://addons.opera.com/en/extensions/details/uget-integration/.

Please consider providing reviews :-)

Thanks & Regards,
Gobinath
