### ISSUE TITLE
Auto download .torrent file Ubuntu 16.04 Chrome Version 55.0.2883.75 (64-bit)

### ISSUE THREAD

**Issue by tuyennn** [slgobinath/uget-chrome-wrapper#11]

**Comment by MichaelTunnell** [comment]
Is this question a problem with uGet not starting the download or with the extension not sending the .torrent file? If the former, then this not a question for this github project but rather a question for uGet.

However, considering I am the Project Manager for uGet, please feel free to clarify.

**Comment by slgobinath** [comment]
Closing this issue as no further updates from the reporter.
