### ISSUE TITLE
Failed to connect with uget-chrome-wrapper in Opera Arch

### ISSUE THREAD

**Issue by slgobinath** [slgobinath/uget-chrome-wrapper#16]
This issue was reported in Opera addon review page. This is due to the inconsistency in Opera native-messaging configuration path. Usually Opera use the same directory as Google Chrome but in Arch AUR pack, it uses `/etc/opera` directory.

I have reproduced this issue and asked the AUR maintainer to release a new PKGBUILD with the fix. Also, I have updated the installation guide for "[Any Linux Systems - Google Chrome and Opera](https://slgobinath.github.io/uget-chrome-wrapper/#manual-installation-for-chrome)"
Until the AUR is updated, follow these steps to integrate Opera with uGet in Arch Linux:

```
sudo mkdir -p /etc/opera/native-messaging-hosts
sudo wget https://raw.githubusercontent.com/slgobinath/uget-chrome-wrapper/master/uget-chrome-wrapper/conf/com.javahelps.ugetchromewrapper.json --output-document /etc/opera/native-messaging-hosts/com.javahelps.ugetchromewrapper.json
```

**Comment by slgobinath** [comment]
I left it open until the AUR is updated.

**Comment by Sasasu** [comment]
AUR has been updated.

**Comment by slgobinath** [comment]
@Sasasu,
Thank you very much for the release.
