### ISSUE TITLE
Support for Mozilla Firefox

### ISSUE THREAD

**Issue by johnp** [slgobinath/uget-chrome-wrapper#18]
With the death of traditional extensions with Firefox 57 a lot of users are going to be in need for a new solution for managing their downloads.
I propose uGet to become the go-to default replacement for all these users. I just found this add-on minutes ago and would suggest adding support for Firefox.
I'm going to try to get it running in my Nightly build later today.

Approximate Userbase of the traditional download managers: [1] 

* DownThemAll! ~1.1 Million Users
* FlashGot ~ 700k Users

and several video downloaders with > 500k - 1 Million users each. 

[1] https://addons.mozilla.org/en-US/firefox/search/?q=download+manager&platform=linux&appver=55.0&sort=users

**Comment by johnp** [comment]
Ok, I've got it mostly working now (that was easy :) ).
Redirects don't seem to work yet and Firefox opens a tab in background with the binary interpreted as ASCII; I'll have a look at that in a couple hours.

**Comment by slgobinath** [comment]
Hi @johnp,
I am little busy these days. Please update your results here (if you have fixed everything that's great :-) ) and I will continue from that later.

Thanks.

**Comment by slgobinath** [comment]
Hi @johnp,
Your PR is merged and I've made some minor bug fixes. After further testings, I will release the Firefox addon. I leave this issue open until I release the Firefox addon.

Thank you very much for your contribution.

**Comment by johnp** [comment]
Thank you for finishing this up, the last few days turned out to be busier for me than expected.

Currently it doesn't work because `hostName` in `background.js` needs to be `com.javahelps.ugetfirefoxwrapper` for the firefox manifest to load (the argument passed to `runtime.sendNativeMessage` needs to equal the filename and the `name` key in the json manifest.

Also, `com.javahelps.ugetfirefoxwrapper.json` may not have a comment block at the top, because that causes the json parser to fail (reported to mozilla, but considered a low priority bug):

    Error parsing native host manifest /usr/lib/mozilla/native-messaging-hosts/com.javahelps.ugetfirefoxwrapper.json: JSON.parse: unexpected character at line 1 column 1 of the JSON data

On windows, you create the file without the license header in the .nsi, so the problem doesn't manifest there.

**Comment by slgobinath** [comment]
Ohh. I'll fix it.

Thanks

**Comment by slgobinath** [comment]
I have made the changes. Also, I've added cookie support even though it is not working. I hope to fix everything asap.

**Comment by slgobinath** [comment]
Hi,
The extension is submitted to Firefox [1] and I am waiting for the approval. I will release the binary for Ubuntu, Arch & Windows after approval.

[1] https://addons.mozilla.org/en-US/firefox/addon/ugetintegration/

**Comment by slgobinath** [comment]
Hi,
All the setup files are released including Windows. Still waiting for the approval from Firefox team. You can test it using developer edition.
