### ISSUE TITLE
Unable to connect to uget-chrome-wrapper - Fx 55

### ISSUE THREAD

**Issue by gbcox** [slgobinath/uget-chrome-wrapper#23]
Running under Fedora 26
Uget 2.1.5
Works fine with Chrome, debugging with Chrome shows:
2017-08-26 23:14:57,251 [INFO]: uget-chrome-wrapper is reading the message
2017-08-26 23:14:57,252 [DEBUG]: Message length: 19
2017-08-26 23:14:57,252 [DEBUG]: Received message: {"version":"2.0.6"}
2017-08-26 23:14:57,290 [DEBUG]: uGet version: 2.1.5
2017-08-26 23:14:57,290 [INFO]: Sending message: {"enable": true, "version": "2.0.4", "uget": "2.1.5"}

With Fx, nothing is written to debug file.
Just get the message of:  Error:  Unable to connect...

Extension installed from:  addons.mozilla.com
v2.0.4

**Comment by slgobinath** [comment]
@gbcox,
How did you install the uget-chrome-wrapper? Did you use the script or manually created the files?

**Comment by gbcox** [comment]
I used the script and followed the instructions here:
https://slgobinath.github.io/uget-chrome-wrapper/#manual-installation-for-all

**Comment by gbcox** [comment]
I did some additional testing and found that it does work, if you install Fx from Mozilla.  If you use the Fedora rpm for Firefox it isn't working.  To recreate and debug you should install Fx from the Fedora repositories.

**Comment by gbcox** [comment]
I found the issue, you have a bug in your script.  
These lines are identical for lib and lib64... you should be downloading to the lib64 directory which you earlier created:

sudo wget https://raw.githubusercontent.com/slgobinath/uget-chrome-wrapper/v2.0.4/uget-chrome-wrapper/conf/com.javahelps.ugetfirefoxwrapper.json --output-document /usr/lib/mozilla/native-messaging-hosts/com.javahelps.ugetfirefoxwrapper.json

Also noticed a few other typos... you have:
# If you don't have Chromium, Google Chrome, Vivaldi or Opera, you can comment the gollowing two lines
should be:
# "following uncommented six lines"
if you're not creating the directories, there is no reason to try to download the files.
Probably should have a de-install option for the script also.

**Comment by slgobinath** [comment]
Thanks for pointing out the script and I have fixed it with the commit: https://github.com/slgobinath/uget-chrome-wrapper/commit/3954969ec6bdb16d80396e16416d9e37de9eb675.

For nothing being interrupted, I will test it in my Fedora virtual machine and let you know. Could you please share the exact Firefox version as well.

FYI: I am using Firefox Nightly 57.0a1 (2017-08-27) (64-bit) in Linux Mint 18.2 and the uGet Integration addon successfully interrupts the downloads. The URL I used for testing is: [Fedora-Workstation-Live-x86_64-26-1.5.iso](https://getfedora.org/en/workstation/download/ws-download-splash?file=https://download.fedoraproject.org/pub/fedora/linux/releases/26/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-26-1.5.iso)

Thanks

**Comment by gbcox** [comment]
I'm running this:  https://koji.fedoraproject.org/koji/buildinfo?buildID=960827
I also noticed the same issue on the version from Mozilla.  Nothing is intercepted.  You are correct, it works on the current nightly... however, instead of opening up a new tab as it does on Chrome, it opens up a new browser window - which you have to manually close.

**Comment by slgobinath** [comment]
Hi @gbcox,
I have tried with Firefox 55 in Fedora 26 and couldn't reproduce this problem. uGet captures the download but there is a known issue of Firefox loading the file as a text content in the tab.
I have released a new extension (2.0.7) which has the fix for that issue. Once Firefox team has approved the new add-on, it will be available to use.

**Comment by gbcox** [comment]
Ok, when it posts I'll give it a try and report back.  Thanks!

**Comment by slgobinath** [comment]
@gbcox the add-on 2.0.7 version was not approved and now 2.0.9 is available. Could you please try this with the new uget-chrome-wrapper 2.0.5.

Steps to follow:
1. Install the latest uget-chrome-wrapper using the same scripts you used earlier
2. Install the latest addon
