### ISSUE TITLE
The firefox addon needs better installation info for linux

### ISSUE THREAD

**Issue by bobafetthotmail** [slgobinath/uget-chrome-wrapper#26]
I just installed your uGet addon on Firefox on OpenSUSE Linux, it's great, thanks for making it. :)

I wanted to report on some difficulties I had to install it.
The main Firefox addon description page does not say that I need to install **uget-chrome-wrapper** too and I don't see post-installation pages telling me that either (at least on OpenSUSE) https://addons.mozilla.org/en-US/firefox/addon/ugetintegration/?src=search
So after I installed the uGet Firefox addon it was not working, I had to google the error message "cannot connect to uget-chrome-wrapper" to get to this git repo and install **uget-chrome-wrapper**.

Can you add in the plugin description or in the plugin popup window that the browser plugin requires **uget-chrome-wrapper** and link to your main site where you state how to install it? https://slgobinath.github.io/uget-chrome-wrapper/

**Comment by slgobinath** [comment]
@bobafetthotmail your suggestions make sense. I will update them soon

Thanks

**Comment by MichaelTunnell** [comment]
I plan on adding instructions to the official uGet website as well. ;)

**Comment by slgobinath** [comment]
Hi @bobafetthotmail,
I have included the links to extensions & add-ons to print at the end of the install script. Further, the addon window now shows a message `For more details and installation guide, visit the Home Page` with a link to https://slgobinath.github.io/uget-chrome-wrapper/.

Do you find it satisfies your requirement? If so, I will close this issue. If you have any suggestions to improve it further, please share it here.

Thanks

**Comment by bobafetthotmail** [comment]
Thanks, it's good now.
