### ISSUE TITLE
update firefox addon to version 2.0.9

### ISSUE THREAD

**Issue by Sasasu** [slgobinath/uget-chrome-wrapper#27]
which is still 2.0.4

https://addons.mozilla.org/en-US/firefox/addon/ugetintegration

**Comment by slgobinath** [comment]
Hi,
I have already uploaded the new version but Mozilla developers take time to manually analyze and approve the addon.
Nowadays I also use Firefox and waiting for my own addon :-(

**Comment by slgobinath** [comment]
Finally, the waiting has come to an end.
Firefox 2.0.9 addon is published. Go and try the `Download all links with uGet` option in the context menu.
To get this option, right-click somewhere on a web page except links.
