### ISSUE TITLE
Chrome edition of Uget wrapper can't detect Python after reinstallation

### ISSUE THREAD

**Issue by NovaViper** [slgobinath/uget-chrome-wrapper#29]
For some reason, ever since I reinstalled Python 3.6.2 (I originally had the 32bit version, now I have the 64 bit), the extension keeps saying "Error: Unable to connect to the uget-chrome-wrapper". I tried the following:
- Uninstall and reinstall Python
- Uninstall and reinstall uGet Wrapper 
- Added all PATH variables for Uget + Wrapper and PYTHON_HOME variable
- Removed and reinstall extension
- Restart computer about 5 times

This happens on Vivaldi 1.11.917.43 (Stable channel) (64-bit)

**Comment by slgobinath** [comment]
Hi,
Again I need some time to test this on my VM. I will update you on coming Monday.

**Comment by slgobinath** [comment]
Hi,
I have tried Python 3.6 with [uGet Chrome Wrapper 2.0.5](https://github.com/slgobinath/uget-chrome-wrapper/releases/download/v2.0.5/uget-chrome-wrapper_2.0.5.0.exe) and uGet Integration extension 2.0.9 but everything works fine in my system.
Could you please make sure that you have these environment variables:

`PATH`
```
C:\Users\<UserName>\AppData\Local\Programs\Python\Python36;C:\uget\bin;C:\Users\<UserName>\AppData\Local\Programs\Python\Python36\Scripts
```

`PYTHONPATH`
```
C:\Users\<UserName>\AppData\Local\Programs\Python\Python36\Lib;C:\Users\<UserName>\AppData\Local\Programs\Python\Python36\Lib\site-packages
```

**Comment by NovaViper** [comment]
I've checked but it still doesn't work. I've completely wiped my computer clean and the extension still doesn't detect the wrapper program

**Comment by NovaViper** [comment]
I've done something like this all in Path: %ProgramFiles%\Python36;%ProgramFiles%\Python36\Scripts;%SystemDrive%\uGet\bin;%SystemDrive%\uGet;

And in PYTHONPATH: %ProgramFiles%\Python36\Lib;%ProgramFiles%\Python36\Lib\site-packages

**Comment by slgobinath** [comment]
The problem seems to be strange.
I will try to produce this in a new VM and let you know.
Meanwhile could you please follow the steps given in https://github.com/slgobinath/uget-chrome-wrapper/issues/20 to enable the log and see if there is a log generated by uget-chrome-wrapper.
To get log output, just start a browser with the extension.

**Comment by NovaViper** [comment]
I can't even get the log to start with Vivaldi or Chrome. loading the extension on chrome gives me the same exact error

**Comment by NovaViper** [comment]
It seems like the extension and/or the program isn't executing at all, as I can't get a log to generate

**Comment by slgobinath** [comment]
I guess the problem is with the program.
I will test it in a new VM today and let you know what happens.

**Comment by slgobinath** [comment]
Now I installed a new Windows 10 in VM with latest Vivaldi, Python 3.6.2 (64 bit) (allowed to create `PATH` variables in the installation wizard), latest uGet (added uget/bin directory to environment variable `PATH`), uget-chrome-wrapper 2.0.5(latest) and the latest uGet Integration extension.

After installing all, I restarted the browser and everything works as expected and I couldn't reproduce the problem :-(

**Comment by NovaViper** [comment]
Did you put path in the system path? I have everything in the system environmental varaibles

**Comment by NovaViper** [comment]
And this is occurring on both computers

**Comment by NovaViper** [comment]
**_WOW_**... Apparently all it took to get it working was a simple reboot of my PC. *Facepalm* Guess even the most simplest solutions make a difference

**Comment by slgobinath** [comment]
I think the modified `PATH` variable was not applied to the system. Usually, we need to restart the system after modifying this variable.

Anyhow if the problem is solved, I can relax :-)
