### ISSUE TITLE
--filename twice?

### ISSUE THREAD

**Issue by AirQuick** [slgobinath/uget-chrome-wrapper#30]
It seems the command line is constructed with the `--filename` arg twice.

https://github.com/slgobinath/uget-chrome-wrapper/blob/c247f2a824c6e3f9c7cbed0299501796c49f9fb2/uget-chrome-wrapper/bin/uget-chrome-wrapper#L160

https://github.com/slgobinath/uget-chrome-wrapper/blob/c247f2a824c6e3f9c7cbed0299501796c49f9fb2/uget-chrome-wrapper/bin/uget-chrome-wrapper#L177

Just wondering if it's really expected.

**Comment by slgobinath** [comment]
Thanks for pointing out this. That was a redundant parameter and fixed with https://github.com/slgobinath/uget-chrome-wrapper/commit/da351063f10c7c3a994aad7110cb32bf0a70b566

**Comment by AirQuick** [comment]
The fix removed the second `--filename`, but I guess you should have removed the first one, otherwise I'm afraid `extract_file_name()` wouldn't take effect.

**Comment by slgobinath** [comment]
@AirQuick thanks for the PR I didn't notice that problem.
