### ISSUE TITLE
Option to disable by extension or site

### ISSUE THREAD

**Issue by proximous** [slgobinath/uget-chrome-wrapper#33]
Love this extension, but is there a way to disable it based on extension or site?

For example, on my banking website, without this extension, I can view PDF statements directly in chrome.  With this, when I try to view a statement, uGET launches, and worse does not correctly download the PDF.

So ideally I would like to have this ignore *.pdf downloads, or tell it to ignore my.bank.com downloads.

Is this possible?

**Comment by slgobinath** [comment]
Hi,
Try adding `pdf, my.bank.com` to `Don't interrupt the urls containing these keywords` text box.

**Comment by proximous** [comment]
Thanks for the reply. That solves it!
