### ISSUE TITLE
Catch all downloads

### ISSUE THREAD

**Issue by DanaMW** [slgobinath/uget-chrome-wrapper#34]
I would like to know if there is a way to catch all downloads. I have the issue where the zip  file  was below the catch size and  now zip is entered in the applications of fire fox. From then on firefox downloads zips and i have to delete the handlers file .  I have zip in the always download and size set to 1 but it still allows the files to go the firefox. So I would like  simply to catch ALL downloads  in uget. Possible?

**Comment by slgobinath** [comment]
If the file is streamed by the server, setting file size to `1` may not work. Try a negative filesize like `-100` and let me know whether it works or not.

However, please note that some strams cannot be successfully downloaded by uGet. Further Google documents are purposefully ignored for a known issue.

**Comment by DanaMW** [comment]
ok I use firefox mostly but have it installed in both. I will let you know.

**Comment by DanaMW** [comment]
I forgot to ask. Can * be used for the always catch filename?

**Comment by slgobinath** [comment]
> I forgot to ask. Can * be used for the always catch filename?

Nope. Regex is not supported yet.

> ok I use firefox mostly but have it installed in both. I will let you know.

I didn't mean Google Chrome but anything from Google drive. The extension does not interrupt any Google drive/Google document files regardless of the browser.

**Comment by DanaMW** [comment]
once zip ends up in handlers.json  then uget doesn't catch it any more so my bet is to just keep them all out by catching them before they get there

**Comment by DanaMW** [comment]
Ok it resets itself to  0 for a size  if the number is a negative number. And on fire fox it has become almost useless the browser is doing all the downloading. Once it downloads a known (to the browser) file type it adds it to the handlers.json and from that point on that file type is no longer passed to uget.
Can you add uget  as a known handler for all file types? if I had that option on the menu i could at least select it and make t permanent. The browser seems to be winning this war. I'm down to using the clipboard to pass files to uget. it is one way that has worked flawless for me.

**Comment by DanaMW** [comment]
Oh and you are using the type of storage in firefox that gets wiped out when the browser is cleaned. (Settings lost) It is my understanding you can use storage.local to prevent that.

**Comment by slgobinath** [comment]
Thanks for the suggestion.
I will move to `storage.local` in the next version.

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/uget-chrome-wrapper/commit/0b262805eaa540417440959483aef8f8ec391d83

**Comment by DanaMW** [comment]
Thank you

**Comment by slgobinath** [comment]
Let's continue the chat here :-)
Now the minimum file size can be set to `-1` and I hope that should catch all the downloads.
I will test it further and update you and leave this issue open until I confirm it.

**Comment by DanaMW** [comment]
And thank you, For at least looking into it

**Comment by DanaMW** [comment]
ok perfect!

**Comment by DanaMW** [comment]
Thank you for your work and changes!

**Comment by slgobinath** [comment]
Hi,
Now you can set `-1` to the minimum file size and which should interrupt all the possible downloads.
If your requirement is satisfied, please close this issue.

Thanks
