### ISSUE TITLE
Garbled filenames

### ISSUE THREAD

**Issue by gyratory** [slgobinath/uget-chrome-wrapper#35]
Firefox Version: Nightly  
Distro: Ubuntu 17.10  
uGet settings: quiet mode enabled for command line, using aria2 as the plugin

Hi, thank you for the work on integrating uGet with Firefox! This is a pretty good replacement for DownThemAll.  

The problem I'm encountering with the Firefox extension has two elements:  
1. Non-ASCII or any non-latin character filename becomes garbled, for example `♥♥♥` turns into `â¥â¥â¥` or `それ` turns into `ãã`
2. Files with special characters (bangs, brackets, etc) in the name are downloaded as [encoded URLs](https://www.thoughtco.com/encoding-urls-3467463). e.g. `Cute! [cats].jpg` turns into `Cute%21 %28cats%29.jpg`  

The first case (mojibake/tofu) is not replicated in Vivaldi but the second case with encoded URLs is. I haven't tried any of the other supported browsers.  
Also, using the `--content-disposition-default-utf8=true` flag in the aria2 plugin settings doesn't seem to affect the downloads passed by Firefox at all.

**Comment by slgobinath** [comment]
The filename passed by the extension has nothing to do with the aria2 or uGet level settings. I will fix this soon.

**Comment by slgobinath** [comment]
Hi,
Could you please check the new extension (2.1.0) and uget-chrome-wrapper (2.0.6) and see whether this problem persists?
If it is still there, please send me the link which causes this problem so that I can test and find the solution.

Thanks

**Comment by gyratory** [comment]
I've updated the extension and wrapper to the latest versions and it works as expected now in Nightly.

Good stuff!
