### ISSUE TITLE
uget downloader is unable to start from few services

### ISSUE THREAD

**Issue by omkarnathsingh** [slgobinath/uget-chrome-wrapper#39]
I have installed uget-chrome-wrapper from PPA in Ubuntu 17.10. 
From few websites like Ubuntu.com when I download .iso files, it starts in uget, but I am unable to download from google drive. Is it a known issue?

**Comment by slgobinath** [comment]
Yup.
Google Drive is not supported purposefully due to this problem: https://askubuntu.com/questions/770753/how-to-download-large-google-drive-file-with-resume-support-in-ubuntu
Also, see https://github.com/slgobinath/uget-chrome-wrapper/issues/6

**Comment by omkarnathsingh** [comment]
Thanks Sir for highlighting the issue. I will try some alternatives.
