### ISSUE TITLE
uget-chrome-wrapper available in aur

### ISSUE THREAD

**Issue by idongyou** [slgobinath/uget-chrome-wrapper#4]
https://aur.archlinux.org/packages/uget-chrome-wrapper

**Comment by slgobinath** [comment]
@idongyou Thank you for your effort on making this available on AUR. I have a suggestion regarding the PKGBUILD. Could you please install `com.javahelps.ugetchromewrapper.json` into both `/etc/opt/chrome/native-messaging-hosts` and `/etc/chromium/native-messaging-hosts` so that users can use it without worrying about their browser (Thats how the [deb](/etc/chromium/native-messaging-hosts) package works).

**Comment by idongyou** [comment]
Sorry, I did not make it clear that my only effort was to release the address of the package on the # archlinux-cn IRC channel. Sasasu is the real Submitter. So I suggest you communicate with him directly. His mailbox is izhaolong0123@gmail.com.
Once again, thank you for solving the problem with chromium.
**My English is very poor, I hope you can understand what I mean**

**Comment by Sasasu** [comment]
I think the user should choose their own browser.
If someone is using chromium, just change 
```
browser=opt/chrome
#browser=chromium #if you use chromium or vivaldi
```
to
```
#browser=opt/chrome
browser=chromium #if you use chromium or vivaldi
```

And my email is **l**izhaolong0123@gmail.com ...

**Comment by Sasasu** [comment]
Maybe work like deb will receive fewer issues. now it is 
```
	#for chrome if you not use chrome please delete them
	mkdir -p "$pkgdir/etc/opt/chrome/native-messaging-hosts"
	install -Dm644 "com.javahelps.ugetchromewrapper.json" "$pkgdir"/etc/opt/chrome/native-messaging-hosts
	
	#for chromium and Vivaldi if you not use chromium or vivaldi please delete them
	mkdir -p "$pkgdir/etc/chromium/native-messaging-hosts"
	install -Dm644 "com.javahelps.ugetchromewrapper.json" "$pkgdir"/etc/chromium/native-messaging-hosts
```
But Arch users should check PKGBUILD by themselves.
[carefully check the PKGBUILD and any .install file for malicious commands. ](https://wiki.archlinux.org/index.php/Arch_User_Repository#Build_and_install_the_package)

**Comment by slgobinath** [comment]
@idongyou @Sasasu Thanks to both of you for your contribution and the site is updated.
