### ISSUE TITLE
Can't install uget-chrome-wrapper.sh

### ISSUE THREAD

**Issue by github-maverick** [slgobinath/uget-chrome-wrapper#41]
The uget-chrome-wrapper.sh file downloaded succesfully but when I tried to run it, it displayed this error:
```
maverick@solus-budgie ~ $ sudo sh install_uget_chrome_wrapper.sh
Password: 
Installing uget-chrome-wrapper v2.0.6
sudo: pam_open_session: System error
sudo: policy plugin failed session initialization
sudo: pam_open_session: System error
sudo: policy plugin failed session initialization
sudo: pam_open_session: System error
sudo: policy plugin failed session initialization
sudo: pam_open_session: System error
sudo: policy plugin failed session initialization
sudo: pam_open_session: System error
sudo: policy plugin failed session initialization
sudo: pam_open_session: System error
sudo: policy plugin failed session initialization
uget-chrome-wrapper is installed successfully!
Please install the 'uGet Integration' extension and restart the browser
  - Google Chrome, Chromium & Vivaldi: https://chrome.google.com/webstore/detail/uget-integration/efjgjleilhflffpbnkaofpmdnajdpepi
  - Mozilla Firefox: https://addons.mozilla.org/en-US/firefox/addon/ugetintegration/
  - Opera: https://addons.opera.com/en/extensions/details/uget-integration
```

and the extension is displaying `Error: Unable to connect to the uget-chrome-wrapper`

**Comment by slgobinath** [comment]
May I know your browser and its architecture (32 bit or 64 bit), operating system and Python 3 version. Also please restart your system and see whether it fixes the problem.

Thanks

**Comment by github-maverick** [comment]
Firefox 56.0.2
Solus 3 Budgie 64 Bit
Python 3.5
I had already restarted twice

**Comment by github-maverick** [comment]
I don't know what was the problem yet.
But I did this in the terminal and it worked.
```
maverick@solus-budgie ~ $ sudo su
root@solus-budgie /home/maverick # sh install_uget_chrome_wrapper.sh
Installing uget-chrome-wrapper v2.0.6
uget-chrome-wrapper is installed successfully!
Please install the 'uGet Integration' extension and restart the browser
  - Google Chrome, Chromium & Vivaldi: https://chrome.google.com/webstore/detail/uget-integration/efjgjleilhflffpbnkaofpmdnajdpepi
  - Mozilla Firefox: https://addons.mozilla.org/en-US/firefox/addon/ugetintegration/
  - Opera: https://addons.opera.com/en/extensions/details/uget-integration
```
I wonder why it didn't install by adding sudo before the command.

**Comment by slgobinath** [comment]
Based on Google search, it is something related to `sudo`. People have reported that they get such problem with `sudo -i` and other commands with sudo.
Since it is not related to `uget-chrome-wrapper` I close this issue.
This link may be useful for you: https://askubuntu.com/questions/170216/sudo-doesnt-work

**Comment by bobafetthotmail** [comment]
@slgobinath might be a good idea to add a line in the generic linux installation instructions https://slgobinath.github.io/uget-chrome-wrapper/#manual-installation-for-all 
to say that if **sudo** isn't working you should use **sudo su** or just **su** to get into a root shell first and then run **sh install_uget_chrome_wrapper.sh** from there.

**Comment by slgobinath** [comment]
@bobafetthotmail sure I will update the document.

Thanks
