### ISSUE TITLE
[Info] The Limitation to the length of the System PATH variable on Windows

### ISSUE THREAD

**Issue by perfectcream** [slgobinath/uget-chrome-wrapper#45]
Hi, @slgobinath

I encountered some strange behaviours when I download files with uGet.
After investigating, I found that, the length of PATH variable on Windows had limitation!!

Please refer the URL below for more details info.

**Limitation to the length of the System PATH variable | Intel® Software**
https://software.intel.com/en-us/articles/limitation-to-the-length-of-the-system-path-variable

**Comment by slgobinath** [comment]
Hi,
Is that the reason for your problem mentioned in issue #43?

> I had try another PATH setting, it works! I can replaces default download manager by uGet Download Manager now (by clicking download link, but It can't intercept Google Drive download).

**Comment by perfectcream** [comment]
Hi, @slgobinath 

There are some connections, but #45 is not the best solution of the problem that I already mentioned in issue #43.

In #43, the issue is uGet should be put in **root directory of disk** (C:\uGet or D:\uget for example).

In #45, the issue is that, if the PATH variable over the limitation, it would be **truncated** by Windows.

There is an example below:

[How do I add to the Windows PATH variable using setx? Having weird problems](https://stackoverflow.com/questions/19287379/how-do-i-add-to-the-windows-path-variable-using-setx-having-weird-problems)

So if users installed some software that are not well written after installing uGet, the PATH of uGet would be **truncated** and lead to a breakdown of uGet Integration.

I suggest this issue can put in the FAQ of setup uGet Integration.

**Comment by slgobinath** [comment]
Hi,
Thanks for the information. I have redesigned the webpage and included this in the [FAQ](https://slgobinath.github.io/uget-chrome-wrapper/#faq) section.
