### ISSUE TITLE
Problem with latest 2.0.7-1

### ISSUE THREAD

**Issue by PaschalisSposito** [slgobinath/uget-chrome-wrapper#51]
Hi,

I installed the latest release but I get the following on Uget extension in both opera and chromium:
Warning: Please upgrade uget-chrome-wrapper to the latest version

I installed from script also and the problem remains....

Also, it does not work... Previous versions were ok.....

I am on Debian 9....

**Comment by DanaMW** [comment]
Also On my chrome browser It was like that before the update but still says "please upgrade..." And after the update the setup stopped working on both Firefox and chrome.

**Comment by DanaMW** [comment]
Also when i installed over 2.0.6 it did not update the *.py file,  had to remove the wrapper and reinstall.

**Comment by slgobinath** [comment]
@PaschalisSposito could you please try removing `uget-chrome-wrapper` manually and install it again?
To remove the file, use the following command:
```
sudo rm /usr/bin/uget-chrome-wrapper
```
@DanaMW it can be a problem with the installer, I will check this.

**Comment by slgobinath** [comment]
@DanaMW Windows installer has been fixed to uninstall the previous version before installing the current version.

**Comment by DanaMW** [comment]
Thank you once again.

**Comment by PaschalisSposito** [comment]
@slgobinath Thanks for your reply. 

I did it, but I get the same "Warning: Please upgrade uget-chrome-wrapper to the latest version" and I cannot download any file....

**Comment by slgobinath** [comment]
Hi @PaschalisSposito,
Could you please check the installed extension version? It should be `2.1.1`.
Sometimes browsers do not upgrade the extension. If the extension is not upgraded you may get the same warning.

**Comment by PaschalisSposito** [comment]
https://addons.opera.com/en/extensions/details/uget-integration/?display=en 2.1.0 is installed to opera... 

newer version exists only at https://chrome.google.com/webstore/detail/uget-integration/efjgjleilhflffpbnkaofpmdnajdpepi/related?utm_source=chrome-app-launcher-info-dialog

**Comment by PaschalisSposito** [comment]
@slgobinath  Why it was not updated?

**Comment by slgobinath** [comment]
My bad.
The extension was rejected due to my mistake in manifest file. I will upload the new version.
Is it working in Chrome?

**Comment by PaschalisSposito** [comment]
Yes.... 
For now I have installed the chrome version to opera and it is working, but of course it is a "hack"....
When the Opera version will be updated?

**Comment by slgobinath** [comment]
I have submitted the updated extension.
Usually opera developers will appprove it within 24 hours though there is no gurantee because they manualy check the code which takes time.

**Comment by PaschalisSposito** [comment]
Thanks for your quick action... I will be waiting for a couple of days.... If there is any problem, I will inform you accordingly....

**Comment by slgobinath** [comment]
Opera addon is now available.
