### ISSUE TITLE
Python3-urllib3 Dependency

### ISSUE THREAD

**Issue by kbicer** [slgobinath/uget-chrome-wrapper#52]
Yesterday i tried the wrapper on Solus OS (relatively new on some development branchs) and failed to get it work because could not install the python-urllib3 on system. It would be great to leave a quick note on installation instructions about python module dependency which is important because program is not working without **python3-urllib3**.

During the research, i saw your note in the codes which was

`sudo apt-get install python3-urllib3`

that helped very much.

**Comment by slgobinath** [comment]
Thanks for pointing it out. I didn't experience any issue with that in my testing environments including Windows so I did not mention it in the document.
I will update the doc soon.
