### ISSUE TITLE
Unable to start/launch uGet

### ISSUE THREAD

**Issue by sparkthedev** [slgobinath/uget-chrome-wrapper#54]
I am using uGet in debian testing. When I first installed uget-chrome-wrapper everything was working fine (uget was already in running state). After restarting system, I am unable to launch uget.
On typing uget-gtk on terminal I have to wait for few minutes for next command but nothing happens.

More Information:
OS: Debian buster/sid
Browsers: Mozilla Firefox 58.0.1 & Chromium 62.0
uGet version: 2.0.10
uget-chrome-wrapper version: 2.0.7

**Comment by slgobinath** [comment]
Hi,
uget-chrome-wrapper does not interfere uGet in anyways. To ensure the issue, could you please remove uget-chrome-wrapper and test uGet alone?

**Comment by sparkthedev** [comment]
On removing uget-chrome-wrapper, uGet still didn't respond. I had to reinstall it. Now its working fine. Thank you for the help! Bro.
You just made uGet as a best DM for Linux platform through your work. Keep up nice work.

Suggestion: As you provided one script (install_uget_chrome_wrapper.sh) to install uget-chrome-wrapper, please provide a script to users to remove it as well. It very painful to remove files one by one by checking their names and location through script.

**Comment by slgobinath** [comment]
Sorry, it is not mentioned in the doc.
However, it is already there https://github.com/slgobinath/uget-chrome-wrapper/blob/master/build/linux/uninstall_uget_chrome_wrapper.sh
