### ISSUE TITLE
Why some files are ignored while some are downloaded

### ISSUE THREAD

**Issue by doylefermi** [slgobinath/uget-chrome-wrapper#7]
![Screencast](https://cloud.githubusercontent.com/assets/8755940/20007864/2e0661c0-a2c4-11e6-9cd6-9d481b1a8c19.gif)

Using the latest version 1.1.2
Some files aren't captured while some are. Is there something to be configured?

**Comment by slgobinath** [comment]
uGet Integration extension captures the downloads with HTTP 200 status if the file size is greater than 300 kb. However, I also noticed that it does not capture the downloads from SaveFrom.net (Earlier it captured them but now I think the SaveFrom.net changed it's own behavior). I am working on it and I will release the fix as soon as possible. thanks for reporting this issue.

Note: If the SaveFrom.net link is opened in a new tab, uget-chrome-wrapper captures them.

**Comment by slgobinath** [comment]
From uGet Integration extension v1.1.3,  an option to `Download with uGet` is added to the right click context menu of links. I hope it will help you until I resolve the exact problem.

This is what you have to do:
1. Right click on the link
2. Select Download with uGet

**Comment by doylefermi** [comment]
Yes that's a good workaround.

The response from SaveFrom.net is a HTTP 302 and its a redirection. I guess HTTP 200 alone shouldn't be considered.

**Comment by slgobinath** [comment]
Fixed with https://github.com/slgobinath/uget-chrome-wrapper/commit/b9d9a19bed38694b6b4088dbddfdc754b5a4667b and the fix is added in v1.1.4.

**Comment by doylefermi** [comment]
Yes that's a perfect fix. Thanks.

But now `Insert` cannot stop capturing the downloads.

Also when downloading from savefrom.net, single click captures the download with filename `videoplayback` while Rightclick->OpenLinkInNewTab captures the original filename.

**Comment by slgobinath** [comment]
Yes I've noticed them. Once I find a fix, I will release a new version :-)

**Comment by slgobinath** [comment]
@doylefermi Please check the new release with uget-chrome-wrapper v1.3.3 and uGet Integration extension v1.1.6.

This version has the following:
 - Ctrl + Shift + U to disable uGet Integration extension temporarily
 - Option to exclude URLs
 - Smart capture from native Chrome download
 - Extract Youtube video file names from the URL generated by SaveFrom.net

**Comment by doylefermi** [comment]
Thanks. It works now.
